export default {
  // Navigacija
  nav: {
    home: 'Početna',
    flights: 'Letovi',
    profile: 'Profil',
    loyalty: 'Loyalty',
    reservations: 'Rezervacije',
    login: 'Prijava',
    register: 'Registracija',
    logout: 'Odjava'
  },

  // Početna stranica
  home: {
    welcome: 'Dobrodošli u Avio Sistem',
    subtitle: 'Rezervišite vaš let brzo i jednostavno',
    searchFlights: 'Pretražite letove',
    manageBookings: 'Upravljajte rezervacijama',
    loyaltyProgram: 'Loyalty program'
  },

  // User Dashboard
  dashboard: {
    welcome: 'Dobrodošli',
    myAccount: 'Moj nalog',
    quickActions: 'Brze akcije',
    recentBookings: 'Nedavne rezervacije',
    upcomingFlights: 'Nadolazeći letovi',
    loyaltyStatus: 'Loyalty status',
    searchNewFlight: 'Pretražite novi let',
    viewAllBookings: 'Pogledajte sve rezervacije',
    manageProfile: 'Upravljajte profilom',
    loyaltyPoints: 'Loyalty bodovi',
    nextFlight: 'Sljedeći let',
    noUpcomingFlights: 'Nemate nadolazećih letova',
    bookNewFlight: 'Rezervišite novi let',
    totalFlights: 'Ukupno letova',
    milesFlown: 'Pređene milje',
    carbonFootprint: 'Ugljeni otisak',
    memberSince: 'Član od',
    accountOverview: 'Pregled naloga',
    flightHistory: 'Historija letova',
    preferences: 'Preferencije'
  },

  // Notifikacije
  notifications: {
    title: 'Obavijesti',
    markAsRead: 'Označi kao pročitano',
    noNewNotifications: 'Nema novih obavijesti'
  },

  // Admin Dashboard
  admin: {
    dashboard: 'Admin Dashboard',
    welcome: 'Dobrodošli, Administrator',
    flightSchedule: 'Raspored letova',
    manageUsers: 'Upravljanje korisnicima',
    manageAircraft: 'Upravljanje avionima',
    manageDestinations: 'Upravljanje destinacijama',
    pricing: 'Cjenovnik',
    airlines: 'Aviokompanije',
    reports: 'Izvještaji',
    settings: 'Podešavanja',
    overview: 'Pregled',
    totalFlights: 'Ukupno letova',
    totalUsers: 'Ukupno korisnika',
    totalBookings: 'Ukupno rezervacija',
    revenue: 'Prihod'
  },

  // Pretraga letova
  flights: {
    title: 'Pretraga Letova',
    from: 'Polazište',
    to: 'Odredište',
    dateFrom: 'Datum od',
    dateTo: 'Datum do',
    airline: 'Aviokompanija',
    class: 'Klasa',
    departureTimeFrom: 'Vrijeme polaska od',
    departureTimeTo: 'Vrijeme polaska do',
    arrivalTimeFrom: 'Vrijeme dolaska od',
    arrivalTimeTo: 'Vrijeme dolaska do',
    search: 'Pretraži',
    noFlightsFound: 'Nema pronađenih letova',
    flightNumber: 'Broj leta',
    departure: 'Polazak',
    arrival: 'Dolazak',
    price: 'Cijena',
    aircraft: 'Avion',
    book: 'Rezerviši',
    loading: 'Učitavanje...',
    error: 'Došlo je do greške pri učitavanju letova.',
    allDestinations: 'Sva odredišta',
    allAirlines: 'Sve aviokompanije',
    economy: 'Ekonomska',
    business: 'Biznis',
    first: 'Prva',
    date: 'Datum',
    time: 'Vrijeme',
    route: 'Ruta'
  },

  // Rezervacija
  booking: {
    title: 'Rezervacija Leta',
    flightDetails: 'Detalji leta',
    passengerInfo: 'Informacije o putnicima',
    paymentInfo: 'Informacije o plaćanju',
    adults: 'Odrasli',
    children: 'Djeca',
    infants: 'Bebe',
    firstName: 'Ime',
    lastName: 'Prezime',
    email: 'Email',
    phone: 'Telefon',
    idNumber: 'Broj ličnog dokumenta',
    birthDate: 'Datum rođenja',
    paymentMethod: 'Način plaćanja',
    cardNumber: 'Broj kartice',
    expiryDate: 'Datum isteka',
    cvc: 'CVC',
    confirm: 'Potvrdi rezervaciju',
    cancel: 'Otkaži',
    seatSelection: 'Odabir sjedišta',
    totalPrice: 'Ukupna cijena',
    bookingConfirmed: 'Rezervacija potvrđena!',
    bookingNumber: 'Broj rezervacije',
    oneWay: 'Jednosmjerna',
    roundTrip: 'Povratna',
    passenger: 'Putnik',
    addPassenger: 'Dodaj putnika',
    removePassenger: 'Ukloni putnika',
    reservationDetails: 'Detalji rezervacije',
    airline: 'Aviokompanija',
    flightNumber: 'Broj leta',
    departure: 'Polazak',
    arrival: 'Dolazak',
    luggage: 'Prtljag dozvoljen',
    luggageInfo: '1 ručni + 1 čekirani (23kg)',
    ticketPrice: 'Cijena jedne karte',
    class: 'Klasa',
    reservationOptions: 'Odaberi opcije rezervacije',
    ticketType: 'Tip karte',
    passengers: 'Putnici',
    enterPassengerData: 'Unesite podatke putnika',
    idPlaceholder: 'Broj pasoša ili ID (XXXXXXXX)',
    namePlaceholder: 'Ime',
    surnamePlaceholder: 'Prezime',
    emailPlaceholder: 'Email',
    phonePlaceholder: 'Telefon',
    birthDatePlaceholder: 'Datum rođenja',
    cardPayment: 'Kartica (Visa/Mastercard)',
    cardNumberPlaceholder: 'Broj kartice',
    month: 'Mjesec',
    year: 'Godina',
    nextToSeatSelection: 'Dalje na odabir sjedišta',
    invalidCardNumber: 'Nevažeći broj kartice. Unesite točno 16 cifara.',
    invalidCVC: 'Nevažeći CVC. Unesite točno 3 cifre.',
    selectExpiryDate: 'Molimo odaberite datum isteka kartice.',
    invalidExpiryFormat: 'Nevažeći datum isteka. Koristite format YYYY-MM.',
    cardExpired: 'Kreditna kartica je istekla. Unesite važeći datum isteka.',
    unknown: 'Nepoznato',
    errorFetchingFlight: 'Nismo mogli dohvatiti podatke o letu.',
    errorFetchingAirlines: 'Greška pri dohvatanju aviokompanija:'
  },

  // Profil
  profile: {
    title: 'Moj Profil',
    personalInfo: 'Lični podaci',
    edit: 'Uredi',
    save: 'Sačuvaj',
    name: 'Ime',
    surname: 'Prezime',
    firstName: 'Ime',
    lastName: 'Prezime',
    email: 'Email',
    phone: 'Telefon',
    registrationDate: 'Datum registracije',
    updateSuccess: 'Profil uspješno ažuriran!',
    updateError: 'Greška pri ažuriranju profila',
    changePassword: 'Promijeni lozinku',
    currentPassword: 'Trenutna lozinka',
    newPassword: 'Nova lozinka',
    confirmPassword: 'Potvrdi lozinku'
  },

  // Loyalty program
  loyalty: {
    title: 'Loyalty Program',
    totalPoints: 'Ukupno bodova',
    availableDiscount: 'Dostupan popust',
    redeemPoints: 'Otkupi bodove',
    pointsHistory: 'Historija bodova',
    flightNumber: 'Broj leta',
    route: 'Ruta',
    date: 'Datum',
    points: 'Bodovi',
    price: 'Cijena',
    redeemSuccess: 'Bodovi uspješno otkupljeni!',
    redeemError: 'Greška pri otkupljivanju bodova',
    notEnoughPoints: 'Nemate dovoljno bodova',
    discountActive: 'Popust je aktivan!',
    earnedPoints: 'Zarađeni bodovi',
    usedPoints: 'Iskorišteni bodovi'
  },

  // Rezervacije
  reservations: {
    title: 'Moje Rezervacije',
    bookingNumber: 'Broj rezervacije',
    flightNumber: 'Broj leta',
    route: 'Ruta', 
    date: 'Datum',
    status: 'Status',
    price: 'Cijena',
    actions: 'Akcije',
    cancel: 'Otkaži',
    modify: 'Promijeni',
    active: 'Aktivna',
    cancelled: 'Otkazana',
    completed: 'Završena',
    cancelSuccess: 'Rezervacija uspješno otkazana',
    cancelError: 'Greška pri otkazivanju rezervacije',
    noReservations: 'Nemate rezervacija',
    viewDetails: 'Pogledaj detalje',
    passengerCount: 'Broj putnika'
  },

  // Login/Register
  auth: {
    login: 'Prijava',
    register: 'Registracija',
    email: 'Email',
    password: 'Lozinka',
    confirmPassword: 'Potvrdi lozinku',
    firstName: 'Ime',
    lastName: 'Prezime',
    phone: 'Telefon',
    loginButton: 'Prijavi se',
    registerButton: 'Registriraj se',
    forgotPassword: 'Zaboravili ste lozinku?',
    alreadyHaveAccount: 'Već imate nalog?',
    dontHaveAccount: 'Nemate nalog?',
    loginSuccess: 'Uspješno ste se prijavili!',
    registerSuccess: 'Uspješno ste se registrirali!',
    loginError: 'Greška pri prijavi',
    registerError: 'Greška pri registraciji',
    resetPassword: 'Resetuj lozinku',
    backToLogin: 'Nazad na prijavu',
    enterEmail: 'Unesite email',
    enterPassword: 'Unesite lozinku',
    enterName: 'Unesite ime',
    enterSurname: 'Unesite prezime',
    fillAllFields: 'Molimo popunite sva polja',
    passwordsDontMatch: 'Lozinke se ne podudaraju',
    forgotPasswordTitle: 'Zaboravljena lozinka',
    forgotPasswordDescription: 'Unesite vašu email adresu da generišemo link za resetovanje lozinke.',
    emailAddress: 'Email adresa',
    enterYourEmail: 'Unesite vaš email',
    generateLink: 'Generiši link',
    tokenGenerated: 'Token za resetovanje je generisan. Koristite link ispod za resetovanje lozinke:',
    resetError: 'Došlo je do greške. Pokušajte ponovo.',
    token: 'Token',
    resetLink: 'Link za resetovanje',
    returnTo: 'Vratite se na'
  },

  // Destinacije
  destinations: {
    title: 'Upravljanje Destinacijama',
    addDestination: 'Dodaj destinaciju',
    editDestination: 'Uredi destinaciju',
    city: 'Grad',
    airportName: 'Naziv aerodroma',
    iataCode: 'IATA kod',
    icaoCode: 'ICAO kod',
    country: 'Zemlja',
    actions: 'Akcije',
    edit: 'Uredi',
    delete: 'Obriši',
    save: 'Sačuvaj',
    cancel: 'Otkaži'
  },

  // Avioni
  aircraft: {
    title: 'Upravljanje Avionima',
    addAircraft: 'Dodaj avion',
    editAircraft: 'Uredi avion',
    name: 'Naziv',
    model: 'Model',
    type: 'Tip',
    registrationNumber: 'Registracijski broj',
    seatConfiguration: 'Konfiguracija sjedala',
    totalSeats: 'Ukupno sjedišta',
    status: 'Status',
    active: 'Aktivan',
    inactive: 'Neaktivan',
    maintenance: 'U održavanju'
  },

  // Korisnici
  users: {
    title: 'Upravljanje Korisnicima',
    totalUsers: 'Ukupno korisnika',
    activeUsers: 'Aktivni korisnici',
    role: 'Uloga',
    admin: 'Administrator',
    customer: 'Kupac',
    registrationDate: 'Datum registracije',
    lastLogin: 'Zadnja prijava',
    block: 'Blokiraj',
    unblock: 'Odblokiraj',
    makeAdmin: 'Napravi administratora',
    removeAdmin: 'Ukloni administratora'
  },

  // Opcenito
  common: {
    yes: 'Da',
    no: 'Ne',
    ok: 'U redu',
    cancel: 'Otkaži',
    save: 'Sačuvaj',
    edit: 'Uredi',
    delete: 'Obriši',
    confirm: 'Potvrdi',
    loading: 'Učitavanje...',
    error: 'Greška',
    success: 'Uspjeh',
    warning: 'Upozorenje',
    info: 'Informacija',
    close: 'Zatvori',
    next: 'Sljedeći',
    previous: 'Prethodni',
    finish: 'Završi',
    required: 'Obavezno polje',
    optional: 'Opcionalno',
    select: 'Odaberi',
    search: 'Pretraži',
    filter: 'Filtriraj',
    sort: 'Sortiraj',
    view: 'Pogledaj',
    download: 'Preuzmi',
    upload: 'Otpremi',
    submit: 'Pošalji',
    reset: 'Resetuj',
    clear: 'Očisti',
    apply: 'Primijeni',
    total: 'Ukupno',
    from: 'Od',
    to: 'Do',
    date: 'Datum',
    time: 'Vrijeme',
    duration: 'Trajanje',
    price: 'Cijena',
    status: 'Status',
    actions: 'Akcije'
  }
}; 