export default {
  // Navigation
  nav: {
    home: 'Home',
    flights: 'Flights',
    profile: 'Profile',
    loyalty: 'Loyalty',
    reservations: 'Reservations',
    login: 'Login',
    register: 'Register',
    logout: 'Logout'
  },

  // Home page
  home: {
    welcome: 'Welcome to Airline System',
    subtitle: 'Book your flight quickly and easily',
    searchFlights: 'Search flights',
    manageBookings: 'Manage bookings',
    loyaltyProgram: 'Loyalty program'
  },

  // User Dashboard
  dashboard: {
    welcome: 'Welcome',
    myAccount: 'My Account',
    quickActions: 'Quick Actions',
    recentBookings: 'Recent Bookings',
    upcomingFlights: 'Upcoming Flights',
    loyaltyStatus: 'Loyalty Status',
    searchNewFlight: 'Search New Flight',
    viewAllBookings: 'View All Bookings',
    manageProfile: 'Manage Profile',
    loyaltyPoints: 'Loyalty Points',
    nextFlight: 'Next Flight',
    noUpcomingFlights: 'No upcoming flights',
    bookNewFlight: 'Book New Flight',
    totalFlights: 'Total Flights',
    milesFlown: 'Miles Flown',
    carbonFootprint: 'Carbon Footprint',
    memberSince: 'Member Since',
    accountOverview: 'Account Overview',
    flightHistory: 'Flight History',
    preferences: 'Preferences'
  },

  // Notifications
  notifications: {
    title: 'Notifications',
    markAsRead: 'Mark as read',
    noNewNotifications: 'No new notifications'
  },

  // Admin Dashboard
  admin: {
    dashboard: 'Admin Dashboard',
    welcome: 'Welcome, Administrator',
    flightSchedule: 'Flight Schedule',
    manageUsers: 'Manage Users',
    manageAircraft: 'Manage Aircraft',
    manageDestinations: 'Manage Destinations',
    pricing: 'Pricing',
    airlines: 'Airlines',
    reports: 'Reports',
    settings: 'Settings',
    overview: 'Overview',
    totalFlights: 'Total Flights',
    totalUsers: 'Total Users',
    totalBookings: 'Total Bookings',
    revenue: 'Revenue'
  },

  // Flight search
  flights: {
    title: 'Flight Search',
    from: 'From',
    to: 'To',
    dateFrom: 'Date from',
    dateTo: 'Date to',
    airline: 'Airline',
    class: 'Class',
    departureTimeFrom: 'Departure time from',
    departureTimeTo: 'Departure time to',
    arrivalTimeFrom: 'Arrival time from',
    arrivalTimeTo: 'Arrival time to',
    search: 'Search',
    noFlightsFound: 'No flights found',
    flightNumber: 'Flight number',
    departure: 'Departure',
    arrival: 'Arrival',
    price: 'Price',
    aircraft: 'Aircraft',
    book: 'Book',
    loading: 'Loading...',
    error: 'Error loading flights.',
    allDestinations: 'All destinations',
    allAirlines: 'All airlines',
    economy: 'Economy',
    business: 'Business',
    first: 'First',
    date: 'Date',
    time: 'Time',
    route: 'Route'
  },

  // Booking
  booking: {
    title: 'Flight Booking',
    flightDetails: 'Flight Details',
    passengerInfo: 'Passenger Information',
    paymentInfo: 'Payment Information',
    adults: 'Adults',
    children: 'Children',
    infants: 'Infants',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    idNumber: 'ID Number',
    birthDate: 'Birth Date',
    paymentMethod: 'Payment Method',
    cardNumber: 'Card Number',
    expiryDate: 'Expiry Date',
    cvc: 'CVC',
    confirm: 'Confirm Booking',
    cancel: 'Cancel',
    seatSelection: 'Seat Selection',
    totalPrice: 'Total Price',
    bookingConfirmed: 'Booking Confirmed!',
    bookingNumber: 'Booking Number',
    oneWay: 'One Way',
    roundTrip: 'Round Trip',
    passenger: 'Passenger',
    addPassenger: 'Add Passenger',
    removePassenger: 'Remove Passenger',
    reservationDetails: 'Reservation Details',
    airline: 'Airline',
    flightNumber: 'Flight Number',
    luggage: 'Luggage Allowance',
    luggageInfo: '1 carry-on + 1 checked (23kg)',
    ticketPrice: 'Ticket Price',
    reservationOptions: 'Select Reservation Options',
    ticketType: 'Ticket Type',
    passengers: 'Passengers',
    enterPassengerData: 'Enter Passenger Data',
    idPlaceholder: 'Passport or ID Number (XXXXXXXX)',
    namePlaceholder: 'First Name',
    surnamePlaceholder: 'Last Name',
    emailPlaceholder: 'Email',
    phonePlaceholder: 'Phone',
    birthDatePlaceholder: 'Birth Date',
    cardPayment: 'Card (Visa/Mastercard)',
    cardNumberPlaceholder: 'Card Number',
    month: 'Month',
    year: 'Year',
    nextToSeatSelection: 'Proceed to Seat Selection',
    invalidCardNumber: 'Invalid card number. Enter exactly 16 digits.',
    invalidCVC: 'Invalid CVC. Enter exactly 3 digits.',
    selectExpiryDate: 'Please select card expiry date.',
    invalidExpiryFormat: 'Invalid expiry date. Use YYYY-MM format.',
    cardExpired: 'Credit card has expired. Enter a valid expiry date.',
    unknown: 'Unknown',
    errorFetchingFlight: 'Could not fetch flight data.',
    errorFetchingAirlines: 'Error fetching airlines:'
  },

  // Profile
  profile: {
    title: 'My Profile',
    personalInfo: 'Personal Information',
    edit: 'Edit',
    save: 'Save',
    name: 'Name',
    surname: 'Surname',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    registrationDate: 'Registration Date',
    updateSuccess: 'Profile updated successfully!',
    updateError: 'Error updating profile',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password'
  },

  // Loyalty program
  loyalty: {
    title: 'Loyalty Program',
    totalPoints: 'Total Points',
    availableDiscount: 'Available Discount',
    redeemPoints: 'Redeem Points',
    pointsHistory: 'Points History',
    flightNumber: 'Flight Number',
    route: 'Route',
    date: 'Date',
    points: 'Points',
    price: 'Price',
    redeemSuccess: 'Points redeemed successfully!',
    redeemError: 'Error redeeming points',
    notEnoughPoints: 'Not enough points',
    discountActive: 'Discount is active!',
    earnedPoints: 'Earned Points',
    usedPoints: 'Used Points'
  },

  // Reservations
  reservations: {
    title: 'My Reservations',
    bookingNumber: 'Booking Number',
    flightNumber: 'Flight Number',
    route: 'Route',
    date: 'Date',
    status: 'Status',
    price: 'Price',
    actions: 'Actions',
    cancel: 'Cancel',
    modify: 'Modify',
    active: 'Active',
    cancelled: 'Cancelled',
    completed: 'Completed',
    cancelSuccess: 'Reservation cancelled successfully',
    cancelError: 'Error cancelling reservation',
    noReservations: 'No reservations',
    viewDetails: 'View Details',
    passengerCount: 'Passenger Count'
  },

  // Login/Register
  auth: {
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    firstName: 'First Name',
    lastName: 'Last Name',
    phone: 'Phone',
    loginButton: 'Sign In',
    registerButton: 'Sign Up',
    forgotPassword: 'Forgot Password?',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: 'Don\'t have an account?',
    loginSuccess: 'Successfully logged in!',
    registerSuccess: 'Successfully registered!',
    loginError: 'Login error',
    registerError: 'Registration error',
    resetPassword: 'Reset Password',
    backToLogin: 'Back to Login',
    enterEmail: 'Enter email',
    enterPassword: 'Enter password',
    enterName: 'Enter name',
    enterSurname: 'Enter surname',
    fillAllFields: 'Please fill in all fields',
    passwordsDontMatch: 'Passwords do not match',
    forgotPasswordTitle: 'Forgot Password',
    forgotPasswordDescription: 'Enter your email address to generate a password reset link.',
    emailAddress: 'Email Address',
    enterYourEmail: 'Enter your email',
    generateLink: 'Generate Link',
    tokenGenerated: 'Reset token has been generated. Use the link below to reset your password:',
    resetError: 'An error occurred. Please try again.',
    token: 'Token',
    resetLink: 'Reset Link',
    returnTo: 'Return to'
  },

  // Destinations
  destinations: {
    title: 'Manage Destinations',
    addDestination: 'Add Destination',
    editDestination: 'Edit Destination',
    city: 'City',
    airportName: 'Airport Name',
    iataCode: 'IATA Code',
    icaoCode: 'ICAO Code',
    country: 'Country',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel'
  },

  // Aircraft
  aircraft: {
    title: 'Manage Aircraft',
    addAircraft: 'Add Aircraft',
    editAircraft: 'Edit Aircraft',
    name: 'Name',
    model: 'Model',
    type: 'Type',
    registrationNumber: 'Registration Number',
    seatConfiguration: 'Seat Configuration',
    totalSeats: 'Total Seats',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    maintenance: 'In Maintenance'
  },

  // Users
  users: {
    title: 'Manage Users',
    totalUsers: 'Total Users',
    activeUsers: 'Active Users',
    role: 'Role',
    admin: 'Administrator',
    customer: 'Customer',
    registrationDate: 'Registration Date',
    lastLogin: 'Last Login',
    block: 'Block',
    unblock: 'Unblock',
    makeAdmin: 'Make Admin',
    removeAdmin: 'Remove Admin'
  },

  // Common
  common: {
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    confirm: 'Confirm',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Information',
    close: 'Close',
    next: 'Next',
    previous: 'Previous',
    finish: 'Finish',
    required: 'Required',
    optional: 'Optional',
    select: 'Select',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    view: 'View',
    download: 'Download',
    upload: 'Upload',
    submit: 'Submit',
    reset: 'Reset',
    clear: 'Clear',
    apply: 'Apply',
    total: 'Total',
    from: 'From',
    to: 'To',
    date: 'Date',
    time: 'Time',
    duration: 'Duration',
    price: 'Price',
    status: 'Status',
    actions: 'Actions'
  }
}; 