export default {
  nav: {
    home: 'Inicio',
    flights: 'Vuelos',
    profile: 'Perfil',
    loyalty: 'Lealtad',
    reservations: 'Reservas',
    login: 'Iniciar sesión',
    register: 'Registrarse',
    logout: 'Cerrar sesión'
  },
  home: {
    welcome: 'Bienvenido al Sistema de Aerolíneas',
    subtitle: 'Reserva tu vuelo rápida y fácilmente',
    searchFlights: 'Buscar vuelos',
    manageBookings: 'Gestionar reservas',
    loyaltyProgram: 'Programa de lealtad'
  },
  dashboard: {
    welcome: 'Bienvenido',
    myAccount: 'Mi Cuenta',
    quickActions: 'Acciones Rápidas',
    recentBookings: 'Reservas Recientes',
    upcomingFlights: 'Próximos Vuelos',
    loyaltyStatus: 'Estado de Lealtad',
    searchNewFlight: 'Buscar Nuevo Vuelo',
    viewAllBookings: 'Ver Todas las Reservas',
    manageProfile: 'Gestionar Perfil',
    loyaltyPoints: 'Puntos de Lealtad',
    nextFlight: 'Próximo Vuelo',
    noUpcomingFlights: 'No hay vuelos próximos',
    bookNewFlight: 'Reservar Nuevo Vuelo',
    totalFlights: 'Total de Vuelos',
    milesFlown: 'Millas Voladas',
    carbonFootprint: 'Huella de Carbono',
    memberSince: 'Miembro Desde',
    accountOverview: 'Resumen de Cuenta',
    flightHistory: 'Historial de Vuelos',
    preferences: 'Preferencias'
  },

  // Notifications
  notifications: {
    title: 'Notificaciones',
    markAsRead: 'Marcar como leído',
    noNewNotifications: 'No hay nuevas notificaciones'
  },

  admin: {
    dashboard: 'Panel de Administrador',
    welcome: 'Bienvenido, Administrador',
    flightSchedule: 'Horario de Vuelos',
    manageUsers: 'Gestionar Usuarios',
    manageAircraft: 'Gestionar Aeronaves',
    manageDestinations: 'Gestionar Destinos',
    pricing: 'Precios',
    airlines: 'Aerolíneas',
    reports: 'Informes',
    settings: 'Configuración',
    overview: 'Vista General',
    totalFlights: 'Total de Vuelos',
    totalUsers: 'Total de Usuarios',
    totalBookings: 'Total de Reservas',
    revenue: 'Ingresos'
  },
  flights: {
    title: 'Búsqueda de Vuelos',
    from: 'Desde',
    to: 'Hasta',
    dateFrom: 'Fecha desde',
    dateTo: 'Fecha hasta',
    airline: 'Aerolínea',
    class: 'Clase',
    departureTimeFrom: 'Hora de salida desde',
    departureTimeTo: 'Hora de salida hasta',
    arrivalTimeFrom: 'Hora de llegada desde',
    arrivalTimeTo: 'Hora de llegada hasta',
    search: 'Buscar',
    noFlightsFound: 'No se encontraron vuelos',
    flightNumber: 'Número de vuelo',
    departure: 'Salida',
    arrival: 'Llegada',
    price: 'Precio',
    aircraft: 'Aeronave',
    book: 'Reservar',
    loading: 'Cargando...',
    error: 'Error al cargar vuelos.',
    allDestinations: 'Todos los destinos',
    allAirlines: 'Todas las aerolíneas',
    economy: 'Económica',
    business: 'Business',
    first: 'Primera',
    date: 'Fecha',
    time: 'Hora',
    route: 'Ruta'
  },
  booking: {
    title: 'Reserva de Vuelo',
    flightDetails: 'Detalles del Vuelo',
    passengerInfo: 'Información del Pasajero',
    paymentInfo: 'Información de Pago',
    adults: 'Adultos',
    children: 'Niños',
    infants: 'Bebés',
    firstName: 'Nombre',
    lastName: 'Apellido',
    email: 'Correo electrónico',
    phone: 'Teléfono',
    idNumber: 'Número de identificación',
    birthDate: 'Fecha de nacimiento',
    paymentMethod: 'Método de pago',
    cardNumber: 'Número de tarjeta',
    expiryDate: 'Fecha de vencimiento',
    cvc: 'CVC',
    confirm: 'Confirmar Reserva',
    cancel: 'Cancelar',
    seatSelection: 'Selección de Asiento',
    totalPrice: 'Precio Total',
    bookingConfirmed: '¡Reserva Confirmada!',
    bookingNumber: 'Número de Reserva',
    oneWay: 'Solo ida',
    roundTrip: 'Ida y vuelta',
    passenger: 'Pasajero',
    addPassenger: 'Agregar Pasajero',
    removePassenger: 'Quitar Pasajero',
    reservationDetails: 'Detalles de la Reserva',
    airline: 'Aerolínea',
    flightNumber: 'Número de Vuelo',
    departure: 'Salida',
    arrival: 'Llegada',
    luggage: 'Equipaje Permitido',
    luggageInfo: '1 de mano + 1 facturado (23kg)',
    ticketPrice: 'Precio del Boleto',
    class: 'Clase',
    reservationOptions: 'Seleccionar Opciones de Reserva',
    ticketType: 'Tipo de Boleto',
    passengers: 'Pasajeros',
    enterPassengerData: 'Ingrese Datos del Pasajero',
    idPlaceholder: 'Número de Pasaporte o ID (XXXXXXXX)',
    namePlaceholder: 'Nombre',
    surnamePlaceholder: 'Apellido',
    emailPlaceholder: 'Correo electrónico',
    phonePlaceholder: 'Teléfono',
    birthDatePlaceholder: 'Fecha de nacimiento',
    cardPayment: 'Tarjeta (Visa/Mastercard)',
    cardNumberPlaceholder: 'Número de tarjeta',
    month: 'Mes',
    year: 'Año',
    nextToSeatSelection: 'Continuar a Selección de Asientos',
    invalidCardNumber: 'Número de tarjeta inválido. Ingrese exactamente 16 dígitos.',
    invalidCVC: 'CVC inválido. Ingrese exactamente 3 dígitos.',
    selectExpiryDate: 'Por favor seleccione la fecha de vencimiento de la tarjeta.',
    invalidExpiryFormat: 'Fecha de vencimiento inválida. Use el formato YYYY-MM.',
    cardExpired: 'La tarjeta de crédito ha expirado. Ingrese una fecha de vencimiento válida.',
    unknown: 'Desconocido',
    errorFetchingFlight: 'No se pudieron obtener los datos del vuelo.',
    errorFetchingAirlines: 'Error al obtener aerolíneas:'
  },
  profile: {
    title: 'Mi Perfil',
    personalInfo: 'Información Personal',
    edit: 'Editar',
    save: 'Guardar',
    name: 'Nombre',
    surname: 'Apellido',
    firstName: 'Nombre',
    lastName: 'Apellido',
    email: 'Correo electrónico',
    phone: 'Teléfono',
    registrationDate: 'Fecha de registro',
    updateSuccess: '¡Perfil actualizado exitosamente!',
    updateError: 'Error al actualizar el perfil',
    changePassword: 'Cambiar Contraseña',
    currentPassword: 'Contraseña Actual',
    newPassword: 'Nueva Contraseña',
    confirmPassword: 'Confirmar Contraseña'
  },
  loyalty: {
    title: 'Programa de Lealtad',
    totalPoints: 'Total de Puntos',
    availableDiscount: 'Descuento Disponible',
    redeemPoints: 'Canjear Puntos',
    pointsHistory: 'Historial de Puntos',
    flightNumber: 'Número de Vuelo',
    route: 'Ruta',
    date: 'Fecha',
    points: 'Puntos',
    price: 'Precio',
    redeemSuccess: '¡Puntos canjeados exitosamente!',
    redeemError: 'Error al canjear puntos',
    notEnoughPoints: 'No hay suficientes puntos',
    discountActive: '¡El descuento está activo!',
    earnedPoints: 'Puntos Ganados',
    usedPoints: 'Puntos Usados'
  },
  reservations: {
    title: 'Mis Reservas',
    bookingNumber: 'Número de Reserva',
    flightNumber: 'Número de Vuelo',
    route: 'Ruta',
    date: 'Fecha',
    status: 'Estado',
    price: 'Precio',
    actions: 'Acciones',
    cancel: 'Cancelar',
    modify: 'Modificar',
    active: 'Activa',
    cancelled: 'Cancelada',
    completed: 'Completada',
    cancelSuccess: 'Reserva cancelada exitosamente',
    cancelError: 'Error al cancelar la reserva',
    noReservations: 'No hay reservas',
    viewDetails: 'Ver Detalles',
    passengerCount: 'Cantidad de Pasajeros'
  },
  auth: {
    login: 'Iniciar sesión',
    register: 'Registrarse',
    email: 'Correo electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    firstName: 'Nombre',
    lastName: 'Apellido',
    phone: 'Teléfono',
    loginButton: 'Iniciar Sesión',
    registerButton: 'Registrarse',
    forgotPassword: '¿Olvidaste tu contraseña?',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    dontHaveAccount: '¿No tienes una cuenta?',
    loginSuccess: '¡Inicio de sesión exitoso!',
    registerSuccess: '¡Registro exitoso!',
    loginError: 'Error de inicio de sesión',
    registerError: 'Error de registro',
    resetPassword: 'Restablecer Contraseña',
    backToLogin: 'Volver al Inicio de Sesión',
    enterEmail: 'Ingresa el correo electrónico',
    enterPassword: 'Ingresa la contraseña',
    enterName: 'Ingresa el nombre',
    enterSurname: 'Ingresa el apellido',
    forgotPasswordTitle: 'Olvidé mi Contraseña',
    forgotPasswordDescription: 'Ingresa tu dirección de correo electrónico para generar un enlace de restablecimiento de contraseña.',
    emailAddress: 'Dirección de Correo Electrónico',
    enterYourEmail: 'Ingresa tu correo electrónico',
    generateLink: 'Generar Enlace',
    tokenGenerated: 'Se ha generado el token de restablecimiento. Usa el enlace de abajo para restablecer tu contraseña:',
    resetError: 'Ocurrió un error. Por favor intenta de nuevo.',
    token: 'Token',
    resetLink: 'Enlace de Restablecimiento',
    returnTo: 'Volver a'
  },
  destinations: {
    title: 'Gestionar Destinos',
    addDestination: 'Agregar Destino',
    editDestination: 'Editar Destino',
    city: 'Ciudad',
    airportName: 'Nombre del Aeropuerto',
    iataCode: 'Código IATA',
    icaoCode: 'Código ICAO',
    country: 'País',
    actions: 'Acciones',
    edit: 'Editar',
    delete: 'Eliminar',
    save: 'Guardar',
    cancel: 'Cancelar'
  },
  aircraft: {
    title: 'Gestionar Aeronaves',
    addAircraft: 'Agregar Aeronave',
    editAircraft: 'Editar Aeronave',
    name: 'Nombre',
    model: 'Modelo',
    type: 'Tipo',
    registrationNumber: 'Número de Registro',
    seatConfiguration: 'Configuración de Asientos',
    totalSeats: 'Total de Asientos',
    status: 'Estado',
    active: 'Activa',
    inactive: 'Inactiva',
    maintenance: 'En Mantenimiento'
  },
  users: {
    title: 'Gestionar Usuarios',
    totalUsers: 'Total de Usuarios',
    activeUsers: 'Usuarios Activos',
    role: 'Rol',
    admin: 'Administrador',
    customer: 'Cliente',
    registrationDate: 'Fecha de Registro',
    lastLogin: 'Último Inicio de Sesión',
    block: 'Bloquear',
    unblock: 'Desbloquear',
    makeAdmin: 'Hacer Administrador',
    removeAdmin: 'Quitar Administrador'
  },
  common: {
    yes: 'Sí',
    no: 'No',
    ok: 'Aceptar',
    cancel: 'Cancelar',
    save: 'Guardar',
    edit: 'Editar',
    delete: 'Eliminar',
    confirm: 'Confirmar',
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    warning: 'Advertencia',
    info: 'Información',
    close: 'Cerrar',
    next: 'Siguiente',
    previous: 'Anterior',
    finish: 'Finalizar',
    required: 'Requerido',
    optional: 'Opcional',
    select: 'Seleccionar',
    search: 'Buscar',
    filter: 'Filtrar',
    sort: 'Ordenar',
    view: 'Ver',
    download: 'Descargar',
    upload: 'Subir',
    submit: 'Enviar',
    reset: 'Restablecer',
    clear: 'Limpiar',
    apply: 'Aplicar',
    total: 'Total',
    from: 'Desde',
    to: 'Hasta',
    date: 'Fecha',
    time: 'Hora',
    duration: 'Duración',
    price: 'Precio',
    status: 'Estado',
    actions: 'Acciones'
  }
}; 