export default {
  nav: {
    home: 'Accueil',
    flights: 'Vols',
    profile: 'Profil',
    loyalty: 'Fidélité',
    reservations: 'Réservations',
    login: 'Connexion',
    register: 'S\'inscrire',
    logout: 'Déconnexion'
  },
  home: {
    welcome: 'Bienvenue dans le Système Aérien',
    subtitle: 'Réservez votre vol rapidement et facilement',
    searchFlights: 'Rechercher des vols',
    manageBookings: 'Gérer les réservations',
    loyaltyProgram: 'Programme de fidélité'
  },
  dashboard: {
    welcome: 'Bienvenue',
    myAccount: 'Mon Compte',
    quickActions: 'Actions Rapides',
    recentBookings: 'Réservations Récentes',
    upcomingFlights: 'Vols à Venir',
    loyaltyStatus: 'Statut de Fidélité',
    searchNewFlight: 'Rechercher Nouveau Vol',
    viewAllBookings: 'Voir Toutes les Réservations',
    manageProfile: 'Gérer le Profil',
    loyaltyPoints: 'Points de Fidélité',
    nextFlight: 'Prochain Vol',
    noUpcomingFlights: 'Aucun vol à venir',
    bookNewFlight: 'Réserver Nouveau Vol',
    totalFlights: 'Total des Vols',
    milesFlown: 'Miles Parcourus',
    carbonFootprint: 'Empreinte Carbone',
    memberSince: 'Membre Depuis',
    accountOverview: 'Aperçu du Compte',
    flightHistory: 'Historique des Vols',
    preferences: 'Préférences'
  },

  // Notifications
  notifications: {
    title: 'Notifications',
    markAsRead: 'Marquer comme lu',
    noNewNotifications: 'Aucune nouvelle notification'
  },

  admin: {
    dashboard: 'Tableau de Bord Administrateur',
    welcome: 'Bienvenue, Administrateur',
    flightSchedule: 'Horaires des Vols',
    manageUsers: 'Gérer les Utilisateurs',
    manageAircraft: 'Gérer les Aéronefs',
    manageDestinations: 'Gérer les Destinations',
    pricing: 'Tarification',
    airlines: 'Compagnies Aériennes',
    reports: 'Rapports',
    settings: 'Paramètres',
    overview: 'Vue d\'ensemble',
    totalFlights: 'Total des Vols',
    totalUsers: 'Total des Utilisateurs',
    totalBookings: 'Total des Réservations',
    revenue: 'Revenus'
  },
  flights: {
    title: 'Recherche de Vols',
    from: 'De',
    to: 'À',
    dateFrom: 'Date de',
    dateTo: 'Date à',
    airline: 'Compagnie aérienne',
    class: 'Classe',
    departureTimeFrom: 'Heure de départ de',
    departureTimeTo: 'Heure de départ à',
    arrivalTimeFrom: 'Heure d\'arrivée de',
    arrivalTimeTo: 'Heure d\'arrivée à',
    search: 'Rechercher',
    noFlightsFound: 'Aucun vol trouvé',
    flightNumber: 'Numéro de vol',
    departure: 'Départ',
    arrival: 'Arrivée',
    price: 'Prix',
    aircraft: 'Aéronef',
    book: 'Réserver',
    loading: 'Chargement...',
    error: 'Erreur lors du chargement des vols.',
    allDestinations: 'Toutes les destinations',
    allAirlines: 'Toutes les compagnies aériennes',
    economy: 'Économique',
    business: 'Affaires',
    first: 'Première',
    date: 'Date',
    time: 'Heure',
    route: 'Route'
  },
  booking: {
    title: 'Réservation de Vol',
    flightDetails: 'Détails du Vol',
    passengerInfo: 'Informations Passager',
    paymentInfo: 'Informations de Paiement',
    adults: 'Adultes',
    children: 'Enfants',
    infants: 'Bébés',
    firstName: 'Prénom',
    lastName: 'Nom de famille',
    email: 'Email',
    phone: 'Téléphone',
    idNumber: 'Numéro d\'identité',
    birthDate: 'Date de naissance',
    paymentMethod: 'Méthode de paiement',
    cardNumber: 'Numéro de carte',
    expiryDate: 'Date d\'expiration',
    cvc: 'CVC',
    confirm: 'Confirmer la Réservation',
    cancel: 'Annuler',
    seatSelection: 'Sélection de Siège',
    totalPrice: 'Prix Total',
    bookingConfirmed: 'Réservation Confirmée !',
    bookingNumber: 'Numéro de Réservation',
    oneWay: 'Aller simple',
    roundTrip: 'Aller-retour',
    passenger: 'Passager',
    addPassenger: 'Ajouter Passager',
    removePassenger: 'Supprimer Passager',
    reservationDetails: 'Détails de la Réservation',
    airline: 'Compagnie Aérienne',
    flightNumber: 'Numéro de Vol',
    luggage: 'Bagages Autorisés',
    luggageInfo: '1 cabine + 1 soute (23kg)',
    ticketPrice: 'Prix du Billet',
    reservationOptions: 'Sélectionner Options de Réservation',
    ticketType: 'Type de Billet',
    passengers: 'Passagers',
    enterPassengerData: 'Saisir Données Passager',
    idPlaceholder: 'Numéro de Passeport ou ID (XXXXXXXX)',
    namePlaceholder: 'Prénom',
    surnamePlaceholder: 'Nom',
    emailPlaceholder: 'E-mail',
    phonePlaceholder: 'Téléphone',
    birthDatePlaceholder: 'Date de naissance',
    cardPayment: 'Carte (Visa/Mastercard)',
    cardNumberPlaceholder: 'Numéro de carte',
    month: 'Mois',
    year: 'Année',
    nextToSeatSelection: 'Continuer vers Sélection des Sièges',
    invalidCardNumber: 'Numéro de carte invalide. Saisissez exactement 16 chiffres.',
    invalidCVC: 'CVC invalide. Saisissez exactement 3 chiffres.',
    selectExpiryDate: 'Veuillez sélectionner la date d\'expiration de la carte.',
    invalidExpiryFormat: 'Date d\'expiration invalide. Utilisez le format YYYY-MM.',
    cardExpired: 'La carte de crédit a expiré. Saisissez une date d\'expiration valide.',
    unknown: 'Inconnu',
    errorFetchingFlight: 'Impossible de récupérer les données du vol.',
    errorFetchingAirlines: 'Erreur lors de la récupération des compagnies aériennes:'
  },
  profile: {
    title: 'Mon Profil',
    personalInfo: 'Informations Personnelles',
    edit: 'Modifier',
    save: 'Enregistrer',
    name: 'Nom',
    surname: 'Nom de famille',
    firstName: 'Prénom',
    lastName: 'Nom de famille',
    email: 'Email',
    phone: 'Téléphone',
    registrationDate: 'Date d\'inscription',
    updateSuccess: 'Profil mis à jour avec succès !',
    updateError: 'Erreur lors de la mise à jour du profil',
    changePassword: 'Changer le Mot de Passe',
    currentPassword: 'Mot de Passe Actuel',
    newPassword: 'Nouveau Mot de Passe',
    confirmPassword: 'Confirmer le Mot de Passe'
  },
  loyalty: {
    title: 'Programme de Fidélité',
    totalPoints: 'Total des Points',
    availableDiscount: 'Remise Disponible',
    redeemPoints: 'Échanger des Points',
    pointsHistory: 'Historique des Points',
    flightNumber: 'Numéro de Vol',
    route: 'Route',
    date: 'Date',
    points: 'Points',
    price: 'Prix',
    redeemSuccess: 'Points échangés avec succès !',
    redeemError: 'Erreur lors de l\'échange des points',
    notEnoughPoints: 'Pas assez de points',
    discountActive: 'La remise est active !',
    earnedPoints: 'Points Gagnés',
    usedPoints: 'Points Utilisés'
  },
  reservations: {
    title: 'Mes Réservations',
    bookingNumber: 'Numéro de Réservation',
    flightNumber: 'Numéro de Vol',
    route: 'Route',
    date: 'Date',
    status: 'Statut',
    price: 'Prix',
    actions: 'Actions',
    cancel: 'Annuler',
    modify: 'Modifier',
    active: 'Active',
    cancelled: 'Annulée',
    completed: 'Terminée',
    cancelSuccess: 'Réservation annulée avec succès',
    cancelError: 'Erreur lors de l\'annulation de la réservation',
    noReservations: 'Aucune réservation',
    viewDetails: 'Voir les Détails',
    passengerCount: 'Nombre de Passagers'
  },
  auth: {
    login: 'Connexion',
    register: 'S\'inscrire',
    email: 'Email',
    password: 'Mot de passe',
    confirmPassword: 'Confirmer le Mot de Passe',
    firstName: 'Prénom',
    lastName: 'Nom de famille',
    phone: 'Téléphone',
    loginButton: 'Se Connecter',
    registerButton: 'S\'inscrire',
    forgotPassword: 'Mot de passe oublié ?',
    alreadyHaveAccount: 'Vous avez déjà un compte ?',
    dontHaveAccount: 'Vous n\'avez pas de compte ?',
    loginSuccess: 'Connexion réussie !',
    registerSuccess: 'Inscription réussie !',
    loginError: 'Erreur de connexion',
    registerError: 'Erreur d\'inscription',
    resetPassword: 'Réinitialiser le Mot de Passe',
    backToLogin: 'Retour à la Connexion',
    enterEmail: 'Entrez l\'email',
    enterPassword: 'Entrez le mot de passe',
    enterName: 'Entrez le prénom',
    enterSurname: 'Entrez le nom de famille',
    forgotPasswordTitle: 'Mot de Passe Oublié',
    forgotPasswordDescription: 'Saisissez votre adresse e-mail pour générer un lien de réinitialisation de mot de passe.',
    emailAddress: 'Adresse E-mail',
    enterYourEmail: 'Saisissez votre e-mail',
    generateLink: 'Générer le Lien',
    tokenGenerated: 'Le token de réinitialisation a été généré. Utilisez le lien ci-dessous pour réinitialiser votre mot de passe:',
    resetError: 'Une erreur s\'est produite. Veuillez réessayer.',
    token: 'Token',
    resetLink: 'Lien de Réinitialisation',
    returnTo: 'Retour à'
  },
  destinations: {
    title: 'Gérer les Destinations',
    addDestination: 'Ajouter une Destination',
    editDestination: 'Modifier la Destination',
    city: 'Ville',
    airportName: 'Nom de l\'Aéroport',
    iataCode: 'Code IATA',
    icaoCode: 'Code ICAO',
    country: 'Pays',
    actions: 'Actions',
    edit: 'Modifier',
    delete: 'Supprimer',
    save: 'Enregistrer',
    cancel: 'Annuler'
  },
  aircraft: {
    title: 'Gérer les Aéronefs',
    addAircraft: 'Ajouter un Aéronef',
    editAircraft: 'Modifier l\'Aéronef',
    name: 'Nom',
    model: 'Modèle',
    type: 'Type',
    registrationNumber: 'Numéro d\'Immatriculation',
    seatConfiguration: 'Configuration des Sièges',
    totalSeats: 'Total des Sièges',
    status: 'Statut',
    active: 'Actif',
    inactive: 'Inactif',
    maintenance: 'En Maintenance'
  },
  users: {
    title: 'Gérer les Utilisateurs',
    totalUsers: 'Total des Utilisateurs',
    activeUsers: 'Utilisateurs Actifs',
    role: 'Rôle',
    admin: 'Administrateur',
    customer: 'Client',
    registrationDate: 'Date d\'Inscription',
    lastLogin: 'Dernière Connexion',
    block: 'Bloquer',
    unblock: 'Débloquer',
    makeAdmin: 'Rendre Administrateur',
    removeAdmin: 'Retirer Administrateur'
  },
  common: {
    yes: 'Oui',
    no: 'Non',
    ok: 'OK',
    cancel: 'Annuler',
    save: 'Enregistrer',
    edit: 'Modifier',
    delete: 'Supprimer',
    confirm: 'Confirmer',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    warning: 'Avertissement',
    info: 'Information',
    close: 'Fermer',
    next: 'Suivant',
    previous: 'Précédent',
    finish: 'Terminer',
    required: 'Obligatoire',
    optional: 'Optionnel',
    select: 'Sélectionner',
    search: 'Rechercher',
    filter: 'Filtrer',
    sort: 'Trier',
    view: 'Voir',
    download: 'Télécharger',
    upload: 'Téléverser',
    submit: 'Soumettre',
    reset: 'Réinitialiser',
    clear: 'Effacer',
    apply: 'Appliquer',
    total: 'Total',
    from: 'De',
    to: 'À',
    date: 'Date',
    time: 'Heure',
    duration: 'Durée',
    price: 'Prix',
    status: 'Statut',
    actions: 'Actions'
  }
}; 