export default {
  nav: {
    home: 'Home',
    flights: 'Voli',
    profile: 'Profilo',
    loyalty: 'Fedeltà',
    reservations: 'Prenotazioni',
    login: 'Accesso',
    register: 'Registrazione',
    logout: 'Disconnetti'
  },
  home: {
    welcome: 'Benvenuto nel Sistema Aereo',
    subtitle: 'Prenota il tuo volo velocemente e facilmente',
    searchFlights: 'Cerca voli',
    manageBookings: 'Gestisci prenotazioni',
    loyaltyProgram: 'Programma fedeltà'
  },
  dashboard: {
    welcome: 'Benvenuto',
    myAccount: 'Il Mio Account',
    quickActions: 'Azioni Rapide',
    recentBookings: 'Prenotazioni Recenti',
    upcomingFlights: 'Voli in Arrivo',
    loyaltyStatus: 'Stato Fedeltà',
    searchNewFlight: 'Cerca Nuovo Volo',
    viewAllBookings: 'Vedi Tutte le Prenotazioni',
    manageProfile: 'Gestisci Profilo',
    loyaltyPoints: 'Punti Fedeltà',
    nextFlight: 'Prossimo Volo',
    noUpcomingFlights: 'Nessun volo in arrivo',
    bookNewFlight: 'Prenota Nuovo Volo',
    totalFlights: 'Voli Totali',
    milesFlown: 'Miglia Volate',
    carbonFootprint: 'Impronta di Carbonio',
    memberSince: 'Membro Dal',
    accountOverview: 'Panoramica Account',
    flightHistory: 'Cronologia Voli',
    preferences: 'Preferenze'
  },

  // Notifications
  notifications: {
    title: 'Notifiche',
    markAsRead: 'Segna come letto',
    noNewNotifications: 'Nessuna nuova notifica'
  },

  admin: {
    dashboard: 'Dashboard Amministratore',
    welcome: 'Benvenuto, Amministratore',
    flightSchedule: 'Programma Voli',
    manageUsers: 'Gestisci Utenti',
    manageAircraft: 'Gestisci Aeromobili',
    manageDestinations: 'Gestisci Destinazioni',
    pricing: 'Prezzi',
    airlines: 'Compagnie Aeree',
    reports: 'Report',
    settings: 'Impostazioni',
    overview: 'Panoramica',
    totalFlights: 'Voli Totali',
    totalUsers: 'Utenti Totali',
    totalBookings: 'Prenotazioni Totali',
    revenue: 'Entrate'
  },
  flights: {
    title: 'Ricerca Voli',
    from: 'Da',
    to: 'A',
    dateFrom: 'Data da',
    dateTo: 'Data a',
    airline: 'Compagnia aerea',
    class: 'Classe',
    departureTimeFrom: 'Orario partenza da',
    departureTimeTo: 'Orario partenza a',
    arrivalTimeFrom: 'Orario arrivo da',
    arrivalTimeTo: 'Orario arrivo a',
    search: 'Cerca',
    noFlightsFound: 'Nessun volo trovato',
    flightNumber: 'Numero volo',
    departure: 'Partenza',
    arrival: 'Arrivo',
    price: 'Prezzo',
    aircraft: 'Aeromobile',
    book: 'Prenota',
    loading: 'Caricamento...',
    error: 'Errore nel caricamento dei voli.',
    allDestinations: 'Tutte le destinazioni',
    allAirlines: 'Tutte le compagnie aeree',
    economy: 'Economy',
    business: 'Business',
    first: 'Prima',
    date: 'Data',
    time: 'Ora',
    route: 'Rotta'
  },
  booking: {
    title: 'Prenotazione Volo',
    flightDetails: 'Dettagli Volo',
    passengerInfo: 'Informazioni Passeggero',
    paymentInfo: 'Informazioni Pagamento',
    adults: 'Adulti',
    children: 'Bambini',
    infants: 'Neonati',
    firstName: 'Nome',
    lastName: 'Cognome',
    email: 'Email',
    phone: 'Telefono',
    idNumber: 'Numero documento',
    birthDate: 'Data di nascita',
    paymentMethod: 'Metodo di pagamento',
    cardNumber: 'Numero carta',
    expiryDate: 'Data di scadenza',
    cvc: 'CVC',
    confirm: 'Conferma Prenotazione',
    cancel: 'Annulla',
    seatSelection: 'Selezione Posto',
    totalPrice: 'Prezzo Totale',
    bookingConfirmed: 'Prenotazione Confermata!',
    bookingNumber: 'Numero Prenotazione',
    oneWay: 'Solo andata',
    roundTrip: 'Andata e ritorno',
    passenger: 'Passeggero',
    addPassenger: 'Aggiungi Passeggero',
    removePassenger: 'Rimuovi Passeggero',
    reservationDetails: 'Dettagli della Prenotazione',
    airline: 'Compagnia Aerea',
    flightNumber: 'Numero Volo',
    departure: 'Partenza',
    arrival: 'Arrivo',
    luggage: 'Bagaglio Consentito',
    luggageInfo: '1 a mano + 1 registrato (23kg)',
    ticketPrice: 'Prezzo Biglietto',
    class: 'Classe',
    reservationOptions: 'Seleziona Opzioni Prenotazione',
    ticketType: 'Tipo Biglietto',
    passengers: 'Passeggeri',
    enterPassengerData: 'Inserisci Dati Passeggero',
    idPlaceholder: 'Numero Passaporto o Documento (XXXXXXXX)',
    namePlaceholder: 'Nome',
    surnamePlaceholder: 'Cognome',
    emailPlaceholder: 'Email',
    phonePlaceholder: 'Telefono',
    birthDatePlaceholder: 'Data di nascita',
    cardPayment: 'Carta (Visa/Mastercard)',
    cardNumberPlaceholder: 'Numero carta',
    month: 'Mese',
    year: 'Anno',
    nextToSeatSelection: 'Procedi alla Selezione del Posto',
    invalidCardNumber: 'Numero carta non valido. Inserisci esattamente 16 cifre.',
    invalidCVC: 'CVC non valido. Inserisci esattamente 3 cifre.',
    selectExpiryDate: 'Seleziona la data di scadenza della carta.',
    invalidExpiryFormat: 'Data di scadenza non valida. Usa il formato YYYY-MM.',
    cardExpired: 'La carta di credito è scaduta. Inserisci una data di scadenza valida.',
    unknown: 'Sconosciuto',
    errorFetchingFlight: 'Impossibile ottenere i dati del volo.',
    errorFetchingAirlines: 'Errore nel recupero delle compagnie aeree:'
  },
  profile: {
    title: 'Il Mio Profilo',
    personalInfo: 'Informazioni Personali',
    edit: 'Modifica',
    save: 'Salva',
    name: 'Nome',
    surname: 'Cognome',
    firstName: 'Nome',
    lastName: 'Cognome',
    email: 'Email',
    phone: 'Telefono',
    registrationDate: 'Data di registrazione',
    updateSuccess: 'Profilo aggiornato con successo!',
    updateError: 'Errore nell\'aggiornamento del profilo',
    changePassword: 'Cambia Password',
    currentPassword: 'Password Attuale',
    newPassword: 'Nuova Password',
    confirmPassword: 'Conferma Password'
  },
  loyalty: {
    title: 'Programma Fedeltà',
    totalPoints: 'Punti Totali',
    availableDiscount: 'Sconto Disponibile',
    redeemPoints: 'Riscatta Punti',
    pointsHistory: 'Cronologia Punti',
    flightNumber: 'Numero Volo',
    route: 'Rotta',
    date: 'Data',
    points: 'Punti',
    price: 'Prezzo',
    redeemSuccess: 'Punti riscattati con successo!',
    redeemError: 'Errore nel riscatto dei punti',
    notEnoughPoints: 'Punti insufficienti',
    discountActive: 'Lo sconto è attivo!',
    earnedPoints: 'Punti Guadagnati',
    usedPoints: 'Punti Utilizzati'
  },
  reservations: {
    title: 'Le Mie Prenotazioni',
    bookingNumber: 'Numero Prenotazione',
    flightNumber: 'Numero Volo',
    route: 'Rotta',
    date: 'Data',
    status: 'Stato',
    price: 'Prezzo',
    actions: 'Azioni',
    cancel: 'Annulla',
    modify: 'Modifica',
    active: 'Attiva',
    cancelled: 'Annullata',
    completed: 'Completata',
    cancelSuccess: 'Prenotazione annullata con successo',
    cancelError: 'Errore nell\'annullamento della prenotazione',
    noReservations: 'Nessuna prenotazione',
    viewDetails: 'Vedi Dettagli',
    passengerCount: 'Numero Passeggeri'
  },
  auth: {
    login: 'Accesso',
    register: 'Registrazione',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Conferma Password',
    firstName: 'Nome',
    lastName: 'Cognome',
    phone: 'Telefono',
    loginButton: 'Accedi',
    registerButton: 'Registrati',
    forgotPassword: 'Hai dimenticato la password?',
    alreadyHaveAccount: 'Hai già un account?',
    dontHaveAccount: 'Non hai un account?',
    loginSuccess: 'Accesso effettuato con successo!',
    registerSuccess: 'Registrazione completata con successo!',
    loginError: 'Errore di accesso',
    registerError: 'Errore di registrazione',
    resetPassword: 'Reimposta Password',
    backToLogin: 'Torna all\'Accesso',
    enterEmail: 'Inserisci email',
    enterPassword: 'Inserisci password',
    enterName: 'Inserisci nome',
    enterSurname: 'Inserisci cognome',
    forgotPasswordTitle: 'Password Dimenticata',
    forgotPasswordDescription: 'Inserisci il tuo indirizzo email per generare un link di reset della password.',
    emailAddress: 'Indirizzo Email',
    enterYourEmail: 'Inserisci la tua email',
    generateLink: 'Genera Link',
    tokenGenerated: 'Il token di reset è stato generato. Usa il link sottostante per resettare la tua password:',
    resetError: 'Si è verificato un errore. Riprova.',
    token: 'Token',
    resetLink: 'Link di Reset',
    returnTo: 'Torna a'
  },
  destinations: {
    title: 'Gestisci Destinazioni',
    addDestination: 'Aggiungi Destinazione',
    editDestination: 'Modifica Destinazione',
    city: 'Città',
    airportName: 'Nome Aeroporto',
    iataCode: 'Codice IATA',
    icaoCode: 'Codice ICAO',
    country: 'Paese',
    actions: 'Azioni',
    edit: 'Modifica',
    delete: 'Elimina',
    save: 'Salva',
    cancel: 'Annulla'
  },
  aircraft: {
    title: 'Gestisci Aeromobili',
    addAircraft: 'Aggiungi Aeromobile',
    editAircraft: 'Modifica Aeromobile',
    name: 'Nome',
    model: 'Modello',
    type: 'Tipo',
    registrationNumber: 'Numero di Registrazione',
    seatConfiguration: 'Configurazione Posti',
    totalSeats: 'Posti Totali',
    status: 'Stato',
    active: 'Attivo',
    inactive: 'Inattivo',
    maintenance: 'In Manutenzione'
  },
  users: {
    title: 'Gestisci Utenti',
    totalUsers: 'Utenti Totali',
    activeUsers: 'Utenti Attivi',
    role: 'Ruolo',
    admin: 'Amministratore',
    customer: 'Cliente',
    registrationDate: 'Data di Registrazione',
    lastLogin: 'Ultimo Accesso',
    block: 'Blocca',
    unblock: 'Sblocca',
    makeAdmin: 'Rendi Amministratore',
    removeAdmin: 'Rimuovi Amministratore'
  },
  common: {
    yes: 'Sì',
    no: 'No',
    ok: 'OK',
    cancel: 'Annulla',
    save: 'Salva',
    edit: 'Modifica',
    delete: 'Elimina',
    confirm: 'Conferma',
    loading: 'Caricamento...',
    error: 'Errore',
    success: 'Successo',
    warning: 'Avviso',
    info: 'Informazione',
    close: 'Chiudi',
    next: 'Successivo',
    previous: 'Precedente',
    finish: 'Fine',
    required: 'Obbligatorio',
    optional: 'Facoltativo',
    select: 'Seleziona',
    search: 'Cerca',
    filter: 'Filtra',
    sort: 'Ordina',
    view: 'Visualizza',
    download: 'Scarica',
    upload: 'Carica',
    submit: 'Invia',
    reset: 'Reimposta',
    clear: 'Cancella',
    apply: 'Applica',
    total: 'Totale',
    from: 'Da',
    to: 'A',
    date: 'Data',
    time: 'Ora',
    duration: 'Durata',
    price: 'Prezzo',
    status: 'Stato',
    actions: 'Azioni'
  }
}; 